export const DEFAULT = {
  FROM: "FROM",
  WHERE: "WHERE?",
  ROUND_TRIP: "Round trip",
  ONE_WAY: "One way",
  DEPARTURE_DATE: "DEPARTURE DATE *",
  RETURN_DATE: "RETURN DATE *",
  PASSENGERS: "PASSENGERS *",
  PASSENGER_ADULT: "Adult",
  SEARCH_FLY: "Search flights",
  WELCOME_TEXT_1: "WHERE",
  WELCOME_TEXT_2: "DO YOU WANT TO",
  WELCOME_TEXT_3: "EXPLORE",
  BLOG: "Blog",
  CONTACTS: "Contacts",
  CLOSE: "Close",
  ABOUT_COMPANY: "About company",
  POPULAR_DESTINATION: "Popular destination",
  HELP_AND_ADVICE: "Help and advice",
  TERMS_AND_CONDITION: "Terms and condition",
  LANGUAGE: "Language",
  EXAMPLE: "Example",
  CITY_FROM: "City from",
  CENTER_OF_CITY: "Center",
  AIRPORT: "Airport",
  TIMEZONE: "Timezone:",
};
