export const ENGLISH = {
  FROM: "FROM",
  WHERE: "WHERE?",
  ROUND_TRIP: "Round trip",
  ONE_WAY: "One way",
  DEPARTURE_DATE: "DEPARTURE DATE *",
  RETURN_DATE: "RETURN DATE *",
  PASSENGERS: "PASSENGERS *",
  PASSENGER_ADULT: "Adult",
  SEARCH_FLY: "Search flights",
  WELCOME_TEXT_1: "WHERE",
  WELCOME_TEXT_2: "DO YOU WANT TO",
  WELCOME_TEXT_3: "EXPLORE",
  BLOG: "Blog",
  CONTACTS: "Contacts",
  CLOSE: "Close",
  ABOUT_COMPANY: "About company",
  POPULAR_DESTINATION: "Popular destination",
  HELP_AND_ADVICE: "Help and advice",
  TERMS_AND_CONDITION: "Terms and condition",
  LANGUAGE: "Language",
  EXAMPLE: "Select",
  CITY_FROM: "City from",
  CENTER_OF_CITY: "Center",
  AIRPORT: "Airport",
  TIMEZONE: "Timezone:",
  NO_RESULT: "No result",
  SEARCH_IN_ANOTHER_WAY: "Try to search in another way",
  GROWN_UPS: "Grown ups",
  CHILDREN: "Children",
  BABIES: "Babies",
  ECONOM: "Econom",
  CONFORT: "Confort",
  BUSINESS: "Business",
  FIRST_CLASS: "First class",
  TYPE_OF_SEAT: "The type of seat on the plane",
  MORE_THAN_12_YEARS: "More than 12 years",
  YEARS_2_12: "2 - 12 years",
  UP_TO_2_YEARS: "Up to 2 years, no place",
  SAVE: "Save",
  SELECT_DEPARTURE_DATE: "Select departure date",
  SELECT_RETURN_DATE: "Select return date",
  REFRESH: "Refresh",
  AIRCRAFT_SEAT_INFO: "Select aircraft seat information",
  TODAY: "TODAY",
};
