export const ROMANIAN = {
  FROM: "ZBOR DIN",
  WHERE: "ATERIZARE ÎN",
  ROUND_TRIP: "Dus-întors",
  ONE_WAY: "Într-o direcție",
  DEPARTURE_DATE: "DATA PLECĂRII *",
  RETURN_DATE: "DATA ÎNTOARCERII *",
  PASSENGERS: "PASAGERI *",
  PASSENGER_ADULT: "Adult",
  SEARCH_FLY: "Căutați zboruri",
  WELCOME_TEXT_1: "UNDE",
  WELCOME_TEXT_2: "DOREȘTI SĂ",
  WELCOME_TEXT_3: "EXPLOREZI",
  BLOG: "Blog",
  CONTACTS: "Contacte",
  CLOSE: "Închide",
  ABOUT_COMPANY: "Despre companie",
  POPULAR_DESTINATION: "Destinații populare",
  HELP_AND_ADVICE: "Ajutor și sfaturi",
  TERMS_AND_CONDITION: "Termeni și condiții",
  LANGUAGE: "Limba",
  EXAMPLE: "Exemplu",
  CITY_FROM: "Oraș din",
  CENTER_OF_CITY: "Centru",
  AIRPORT: "Aeroport",
  TIMEZONE: "Fus orar:",

};
