export const ROMANIAN = {
  FROM: "ZBOR DIN",
  WHERE: "ATERIZARE ÎN",
  ROUND_TRIP: "Dus-întors",
  ONE_WAY: "Într-o direcție",
  DEPARTURE_DATE: "DATA PLECĂRII *",
  RETURN_DATE: "DATA ÎNTOARCERII *",
  PASSENGERS: "PASAGERI *",
  PASSENGER_ADULT: "Adult",
  SEARCH_FLY: "Căutați zboruri",
  WELCOME_TEXT_1: "UNDE",
  WELCOME_TEXT_2: "DOREȘTI SĂ",
  WELCOME_TEXT_3: "EXPLOREZI",
  BLOG: "Blog",
  CONTACTS: "Contacte",
  CLOSE: "Închide",
  ABOUT_COMPANY: "Despre companie",
  POPULAR_DESTINATION: "Destinații populare",
  HELP_AND_ADVICE: "Ajutor și sfaturi",
  TERMS_AND_CONDITION: "Termeni și condiții",
  LANGUAGE: "Limba",
  EXAMPLE: "Selectează",
  CITY_FROM: "Oraș din",
  CENTER_OF_CITY: "Centru",
  AIRPORT: "Aeroport",
  TIMEZONE: "Fus orar:",
  NO_RESULT: "Nici un rezultat",
  SEARCH_IN_ANOTHER_WAY: "Încercați să căutați în alt mod",
  GROWN_UPS: "Adulți",
  CHILDREN: "Copii",
  BABIES: "Bebeluși",
  ECONOM: "Econom",
  CONFORT: "Confort",
  BUSINESS: "Business",
  FIRST_CLASS: "Prima clasă",
  TYPE_OF_SEAT: "Tipul scaunului în avion",
  MORE_THAN_12_YEARS: "Mai mari de 12 ani",
  YEARS_2_12: "2 - 12 ani",
  UP_TO_2_YEARS: "Până la 2 ani, fără loc",
  SAVE: "Salviază",
  SELECT_DEPARTURE_DATE: "Selectați data plecării",
  SELECT_RETURN_DATE: "Selectați data întoarcerii",
  REFRESH: "Reseteză",
  AIRCRAFT_SEAT_INFO: "Selectați informația despre locul în avion",
  TODAY: "ASTĂZI",

  STOPOVER: "Escală",
  COMPANIES: "Companii",
  SEATS: "Locuri",
  PASSENGERS_SMALL: "Pasageri",
  BAGGAGE: "Bagaj",
  TYPE: "Tip",
  PRICE: "Preț",
  NO: "nu",
  AVAILABLE: "disponibile",
  INCLUDED: "inclus",
  DETAILS: "Detalii",
  EDIT: "EDITEAZĂ",
};
