export enum AIRPANE_ORIENTATION {
  UP = "UP",
  DOWN = "DOWN",
}

export enum LANGUAGES {
  RO = "RO",
  EN = "EN",
}

export enum LOCALIZATION_ID {
  FROM = "FROM",
  WHERE = "WHERE",
  ROUND_TRIP = "ROUND_TRIP",
  ONE_WAY = "ONE_WAY",
  DEPARTURE_DATE = "DEPARTURE_DATE",
  RETURN_DATE = "RETURN_DATE",
  PASSENGERS = "PASSENGERS",
  PASSENGER_ADULT = "PASSENGER_ADULT",
  SEARCH_FLY = "SEARCH_FLY",
  WELCOME_TEXT_1 = "WELCOME_TEXT_1",
  WELCOME_TEXT_2 = "WELCOME_TEXT_2",
  WELCOME_TEXT_3 = "WELCOME_TEXT_3",
  BLOG = "BLOG",
  CONTACTS = "CONTACTS",
  CLOSE = "CLOSE",
}
