export enum AIRPANE_ORIENTATION {
  UP = "UP",
  DOWN = "DOWN",
}

export enum LANGUAGES {
  RO = "RO",
  EN = "EN",
}

export enum REDUCERS_NAME {
  LANGUAGE = "language",
  SIDEBAR_MENU = "sidebarMenu",
  DROPDOWN_SEARCH = "dropdownSearch",
}

export enum DESTINATION_SEARCH_TYPE {
  FROM = "FROM",
  WHERE = "WHERE",
}

export enum LOCATIONS_REQUEST_TYPE {
  COUNTRY_CODE = "COUNTRY_CODE",
}

export enum AIRFLY_PLACE_TYPE {
  ECONOM = "ECONOM",
  CONFORT = "CONFORT",
  BUSINESS = "BUSINESS",
  FIRST_CLASS = "FIRST_CLASS",
}

export enum LOCALIZATION_ID {
  FROM = "FROM",
  WHERE = "WHERE",
  ROUND_TRIP = "ROUND_TRIP",
  ONE_WAY = "ONE_WAY",
  DEPARTURE_DATE = "DEPARTURE_DATE",
  RETURN_DATE = "RETURN_DATE",
  PASSENGERS = "PASSENGERS",
  PASSENGER_ADULT = "PASSENGER_ADULT",
  SEARCH_FLY = "SEARCH_FLY",
  WELCOME_TEXT_1 = "WELCOME_TEXT_1",
  WELCOME_TEXT_2 = "WELCOME_TEXT_2",
  WELCOME_TEXT_3 = "WELCOME_TEXT_3",
  BLOG = "BLOG",
  CONTACTS = "CONTACTS",
  CLOSE = "CLOSE",
  ABOUT_COMPANY = "ABOUT_COMPANY",
  POPULAR_DESTINATION = "POPULAR_DESTINATION",
  HELP_AND_ADVICE = "HELP_AND_ADVICE",
  TERMS_AND_CONDITION = "TERMS_AND_CONDITION",
  LANGUAGE = "LANGUAGE",
  EXAMPLE = "EXAMPLE",
  CITY_FROM = "CITY_FROM",
  CENTER_OF_CITY = "CENTER_OF_CITY",
  AIRPORT = "AIRPORT",
  TIMEZONE = "TIMEZONE",
  NO_RESULT = "NO_RESULT",
  SEARCH_IN_ANOTHER_WAY = "SEARCH_IN_ANOTHER_WAY",
  GROWN_UPS = "GROWN_UPS",
  CHILDREN = "CHILDREN",
  BABIES = "BABIES",
  ECONOM = "ECONOM",
  CONFORT = "CONFORT",
  BUSINESS = "BUSINESS",
  FIRST_CLASS = "FIRST_CLASS",
  TYPE_OF_SEAT = "TYPE_OF_SEAT",
  MORE_THAN_12_YEARS = "MORE_THAN_12_YEARS",
  YEARS_2_12 = "YEARS_2_12",
  UP_TO_2_YEARS = "UP_TO_2_YEARS",
  SAVE = "SAVE",
  SELECT_DEPARTURE_DATE = "SELECT_DEPARTURE_DATE",
  SELECT_RETURN_DATE = "SELECT_RETURN_DATE",
  REFRESH = "REFRESH",
  AIRCRAFT_SEAT_INFO = "AIRCRAFT_SEAT_INFO",
  TODAY = "TODAY",
}
